version: '3'

services:
  wyoming-whisper:
    image: rhasspy/wyoming-whisper:latest
    restart: unless-stopped
    ports:
      - 10300:10300
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    volumes:
      - /data/wyoming-whisper:/data
    environment:
      - WHISPER_MODEL=medium
      - WHISPER_LANGUAGE=en
    command: --model medium --language en --uri 'tcp://0.0.0.0:10300'
    networks:
      - app_network

networks:
  app_network:
    external: true
