services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
    environment:
      - N8N_HOST=n8n-beast.fucksafety.com
      - N8N_PORT=443
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n-beast.fucksafety.com/
      # - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      # - WEBHOOK_URL=${N8N_WEBHOOK_URL}
    networks:
      - app_network
      - proxy_network

volumes:
  n8n_data:
    external: false

networks:
  app_network:
    external: true
  proxy_network:
    external: true

