services:
  cloudflared-capturebrain:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNN_CAPTUREBRAIN}
    env_file:
      - .env
