version: '3'

services:
  piper:
    image: rhasspy/wyoming-piper:latest
    restart: unless-stopped
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    volumes:
      - /data/piper:/data
    command: --voice en-us-ryan-high --uri 'tcp://0.0.0.0:10200'
    networks:
      - app_network

networks:
  app_network:
    external: true
