FROM universonic/stable-diffusion-webui:latest

# Set the working directory
WORKDIR /app/stable-diffusion-webui/extensions

# Clone the extensions
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-pixelization
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-promptgen
