networks:
  app_network:
    driver: bridge
  proxy_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/ollama
  openwebui_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/openwebui
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/searxng/redis
  n8n_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/n8n
  nginx_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/nginx/data
  nginx_letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/nginx/letsencrypt

