services:
  registry:
    build:
      context: .
      dockerfile: Dockerfile.registry
    # image: registry:2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry_data:/var/lib/registry
      - /data/registry/auth:/auth
    ports:
      - "5000:5000"
    networks:
      - app_network
      - proxy_network
    healthcheck:
      test: ["CMD", "curl", "-u", "${REGISTRY_USER}:${REGISTRY_PASSWORD}", "-f", "http://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  registry_data:
    external: true

networks:
  app_network:
    external: true
  proxy_network:
    external: true 
