services:
  wyoming-whisper:
    image: rhasspy/wyoming-whisper:latest
    container_name: wyoming-whisper
    restart: unless-stopped
    ports:
      - 10300:10300
    volumes:
      - /data/wyoming-whisper:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - WHISPER_MODEL=medium
      - WHISPER_LANGUAGE=en
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USE_GPU=1
    runtime: nvidia  # Specify the NVIDIA runtime
    command: --model medium --language en --uri 'tcp://0.0.0.0:10300'
    networks:
      - app_network

networks:
  app_network:
    external: true
