services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "7000:8080"
    volumes:
      - openwebui_data:/app/backend/data
    deploy:  
      resources:  
        reservations:  
          devices:  
            - driver: nvidia  
              count: all  
              capabilities:  
                - gpu  
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    networks:
      - app_network
      - proxy_network

volumes:
  openwebui_data:
    external: true

networks:
  app_network:
    external: true
  proxy_network:
    external: true

