services:
  stable-diffusion-webui:
    image: universonic/stable-diffusion-webui:latest
    container_name: stable-diffusion
    restart: unless-stopped
    privileged: true
    volumes:
      - stable_diffusion_data:/app/stable-diffusion-webui
      - /data/stable-diffusion/models:/app/stable-diffusion-webui/models
      - /data/stable-diffusion/outputs:/app/stable-diffusion-webui/outputs
      - /data/stable-diffusion/extensions:/app/stable-diffusion-webui/extensions
    ports:
      - "7860:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    runtime: nvidia
    networks:
      - app_network

volumes:
  stable_diffusion_data:
    external: false

networks:
  app_network:
    external: true
