services:
  piper:
    image: rhasspy/wyoming-piper:latest
    container_name: piper
    restart: unless-stopped
    ports:
      - 10200:10200
    volumes:
      - /data/piper:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USE_GPU=1
    runtime: nvidia
    command: --voice en-us-ryan-high --uri 'tcp://0.0.0.0:10200'
    networks:
      - app_network

networks:
  app_network:
    external: true

